spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/configdb
    username: postgresDB
    password: pass123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: false #true
